repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
#-   repo: https://github.com/psf/black
    #rev: 19.3b0
    #hooks:
    #-   id: black

#https://github.com/pre-commit/pre-commit/issues/761#issuecomment-394167542
# -   repo: local
#     hooks:
#     -   id: pytest
#         name: pytest
#         entry: /home/pnr/anaconda3/envs/ResSim/bin/pytest
#         language: script
#         pass_filenames: false
#         # alternatively you could `types: [python]` so it only runs when python files change
#         # though tests might be invalidated if you were to say change a data file
#         always_run: true
